config/routes.rb
Rails.application.routes.draw do
 

  resources :students
 
  root 'students#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
    validates :name, :weight, :height, :color, :gpa, :email, presence: true 
    validates_numericality_of :height, :weight, :gpa

                    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
    
    
  helper_method :sort_column, :sort_direction
  def index
    @students = Student.order(sort_column + ' ' + sort_direction)
  end
  
  
 
    def show
        @students = Student.find(params[:id])
    end
 
    def new
        @students = Student.new
    end
 
    def edit
        @students = Student.find(params[:id])
    end
 
    def create
        @students = Student.new(students_params)
 
        if @students.save
            redirect_to @students
        else
            render 'new'
        end
    end
 
    def update
        @students = Student.find(params[:id])
 
        if @students.update(students_params)
            redirect_to @students
        else
            render 'edit'
        end
    end
 
    def destroy
        @students = Student.find(params[:id])
        @students.destroy
 
        redirect_to students_path
    end
 
    private
    def students_params
      params.require(:student).permit(:name, :height, :weight, :color, :gpa, :email)
    end
 
 private
  def sort_column
    params[:sort] || "name"
  end
  
  def sort_direction
    params[:direction] || "asc"
  end
    
 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @students do |f| %>
 
  <% if @students.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@students.errors.count, "error") %> prohibited
        this students from being saved:
      </h2>
      <ul  style= "list-style-position: inside;" >
        <% @students.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </p>
  
  <p>
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </p>
  
  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>
  
  <p>
    <%= f.label :gpa %><br>
    <%= f.text_field :gpa %>
  </p>
  
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>


<style>
body{
  text-align:center;
}
  
</style>

app/views/students/edit.html.erb
<body>
<h1 style= "color:gray">Edit Student Information</h1>
<hr style="color:light-gray; height: 10px; border: 0;box-shadow: 0 10px 10px -10px #8c8b8b inset;">
 
<%= render 'form' %>
 
<%= link_to image_tag("back.png", :title => "Back"), students_path %> 
</body>
<style>
    body{
        text-align:center;
        font-family:sans-serif;
    }
    
</style>

app/views/students/index.html.erb
<h1 style= "text-align:center; color:gray">Student Information</h1>
<h3 style= "text-align:center;"><%= link_to 'Add New Student!', new_student_path %></h3>

<body>
<hr style="color:light-gray; height: 10px; border: 0;box-shadow: 0 10px 10px -10px #8c8b8b inset;">
<h4 style= "text-align:center">
<span>Sort by: </span>
<%= sortable "Name " %>
<%= sortable "Height " %>
<%= sortable "Weight " %>
<%= sortable "GPA " %>
<%= sortable "email" %></h4>

<hr style="color:light-gray;">
</body>


<style>

body{
  font-family:sans-serif;
  
}

#fixed-size-square {
    display:inline-table;
    background: white;
    border: solid;
    border-color:black;
    border-width:1px;
    vertical-align: bottom;
   
}

#text-box{
  display: table-cell;
  vertical-align: middle;
  text-align: center;
}
 
</style>

<div>
  <% @students.each do |student| %>
     
    <div id= "fixed-size-square" style = "width:<%= student.weight%>px; height:<%= student.height %>px">
       <div id= "text-box" style = "width:<%= student.weight %> px; 
                    height:<%= student.height %>  px;
                    color:<%= student.color %>;">
         <b><%= student.name %></b><br><b><%= student.gpa %></b><br><b><%= student.email %></b><br><br>
         
        
        <div style= "vertical-align:bottom" >
            <%= link_to image_tag("show.png", :title => "Show"), student_path(student) %>
            <%= link_to image_tag("edit.png", :title => "Edit"), edit_student_path(student) %>
            <%= link_to image_tag("delete.png", :title => "Delete"), student_path(student),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
          
        </div>
       
                    
        </div>
    </div>
    
  <% end %>

</div>

app/views/students/new.html.erb
<body>
<h1 style= "color:gray">New Student Entry</h1>
<hr>

 <%= render 'form' %>

<%= link_to image_tag("back.png", :title => "Back"), students_path %> 
</body>

<style>
    body{
        font-family:sans-serif;
        text-align:center;
    }
    
</style>

app/views/students/show.html.erb
<body>
<h1 style= "color:gray">Detail Information</h1>
<hr style="color:light-gray; height: 10px; border: 0;box-shadow: 0 10px 10px -10px #8c8b8b inset;">
<p>
  <strong>Name:</strong>
  <%= @students.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @students.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @students.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @students.color %>
</p>

<p>
  <strong>GPA:</strong>
  <%= @students.gpa %>
</p>

 
<p>
  <strong>Email:</strong>
  <%= @students.email %>
</p>



<%= link_to image_tag("back.png", :title => "Back"), students_path %> |
<%= link_to image_tag("edit.png", :title => "Edit"), edit_student_path(@students) %>
</body>
  
<style>

body{
  font-family:sans-serif;
  text-align:center;
}

</style>

app/views/welcome/index.html.erb
<h1>Student Data!</h1>

<%= link_to 'View', controller: 'students' %>